# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'DictionaryIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DictionaryIOS
pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'
pod 'RxRealm',:git => 'https://github.com/RxSwiftCommunity/RxRealm',:tag => '0.7.4’
end
